import {validDate,uid,weekday,addDays,round} from './utils.js';import {activeOn,employeeOn} from './employees.js';import {audit} from './storage.js';import {holidayOn} from './holidays.js';import {selectRule} from './statutory.js';
export const attendanceStatuses=['Present','Absent','Late','Undertime','Paid Leave','Unpaid Leave','Rest Day','Regular Holiday','Special Non-Working Day'];
const minutes=t=>{if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(t||''))throw Error('Use valid clock times.');const [h,m]=t.split(':').map(Number);return h*60+m};
export function isRest(e,date){const day=weekday(date),rest=Number(e.restDay);const distance=(day-rest+7)%7;return distance===0||distance>Number(e.normalDays)}
export function calculateAttendance(a,e){const noWork=['Absent','Unpaid Leave','Paid Leave'].includes(a.status)||!a.timeIn&&!a.timeOut;if(noWork)return {totalMinutes:0,regularMinutes:0,overtimeMinutes:0,lateMinutes:0,undertimeMinutes:0,nightMinutes:0,worked:[],breakMinutes:0};const start=minutes(a.timeIn);let end=minutes(a.timeOut)+(a.overnight?1440:0);if(end<=start||end-start>1440)throw Error('Clock-out must follow clock-in (select overnight when needed).');const breakM=Number(a.breakMinutes||0);if(breakM<0||breakM>=end-start)throw Error('Break must be shorter than the shift.');let bs=breakM?minutes(a.breakStart):end;if(bs<start)bs+=1440;if(breakM&&(bs<start||bs+breakM>end))throw Error('Break must be inside the shift.');const worked=[];for(let m=start;m<end;m++)if(m<bs||m>=bs+breakM)worked.push(m);const normal=round(e.normalHours*60);const schedule=minutes(e.scheduleIn);let scheduleOut=minutes(e.scheduleOut);if(scheduleOut<=schedule)scheduleOut+=1440;const late=Math.max(0,start-schedule);const undertime=Math.max(0,scheduleOut-end);return {totalMinutes:worked.length,regularMinutes:Math.min(normal,worked.length),overtimeMinutes:Math.max(0,worked.length-normal),lateMinutes:late,undertimeMinutes:undertime,nightMinutes:worked.filter(m=>m%1440>=1320||m%1440<360).length,worked,breakMinutes:breakM}}
export function saveAttendance(state,a){if(!validDate(a.date)||!attendanceStatuses.includes(a.status))throw Error('Valid attendance date and status are required.');const e=state.employees.find(e=>e.id===a.employeeId);if(!e||!activeOn(e,a.date))throw Error('Employee is inactive on this date. Restore employment status first.');if(state.closures.some(c=>c.month===a.date.slice(0,7)&&c.status==='Closed'))throw Error('This month is locked.');if(state.payrolls.some(p=>['Approved','Paid'].includes(p.status)&&p.kind==='Regular'&&p.period.from<=a.date&&p.period.to>=a.date&&p.lines.some(l=>l.employeeId===e.id)))throw Error('Attendance is part of a finalized payroll. Create a payroll adjustment.');if(state.attendance.some(x=>x.employeeId===a.employeeId&&x.date===a.date&&x.id!==a.id))throw Error('Attendance already exists for this employee and date.');const computed=calculateAttendance(a,employeeOn(e,a.date));if(computed.totalMinutes){const start=Date.parse(a.date+'T'+a.timeIn+':00Z'),end=Date.parse(a.date+'T'+a.timeOut+':00Z')+(a.overnight?86400000:0);for(const other of state.attendance.filter(x=>x.employeeId===e.id&&x.id!==a.id&&x.timeIn&&x.timeOut)){const os=Date.parse(other.date+'T'+other.timeIn+':00Z'),oe=Date.parse(other.date+'T'+other.timeOut+':00Z')+(other.overnight?86400000:0);if(start<oe&&end>os)throw Error('This shift overlaps another attendance record.')}}const old=state.attendance.find(x=>x.id===a.id);if(old&&!a.note?.trim())throw Error('An audit note is required for corrections.');const item={...a,id:old?.id||uid('ATT')};if(old)state.attendance[state.attendance.indexOf(old)]=item;else state.attendance.push(item);audit(state,old?'Attendance edited':'Attendance created',e.code,old||null,item);return item}
export function payDay(state,a,e){const metrics=calculateAttendance(a,e);const earnings={basic:0,overtime:0,holiday:0,restDay:0,night:0,paidLeave:0};const details=[];const holiday=holidayOn(state,a.date,e.branch);const rest=isRest(e,a.date),normal=e.normalHours*60;const baseline=e.payrollType==='Monthly';if(a.status==='Paid Leave'){earnings.paidLeave=baseline?0:e.dailyRate;return {earnings,metrics,details,qualifiedBasic:0,unearned:0}}
if(!metrics.totalMinutes){if(holiday?.type==='Regular Holiday'&&a.holidayEligible){earnings.holiday=baseline?0:e.dailyRate;details.push({date:a.date,label:'Unworked regular holiday',minutes:normal,multiplier:1,amount:earnings.holiday})}return {earnings,metrics,details,qualifiedBasic:0,unearned:!rest&&(!holiday||holiday.type==='Special Working Day')?e.dailyRate:0}}
// Minute segmentation allocates cross-midnight holiday/rest/NSD premiums correctly.
const buckets=new Map();metrics.worked.forEach((minute,index)=>{const d=addDays(a.date,Math.floor(minute/1440)),h=holidayOn(state,d,e.branch),r=isRest(e,d),rule=selectRule(state,'premiums',d);const v=rule.values;const type=h?.type==='Regular Holiday'?(r?'regularHolidayRestDay':'regularHoliday'):h?.type==='Special Non-Working Day'?(r?'specialDayRestDay':'specialDay'):h?.type==='Company Holiday'?'companyHoliday':r?'restDay':'ordinary';const ot=index>=normal;const multiplier=v[type+(ot?'OT':'')];const hour=(minute%1440)/60;const night=v.nightStart>v.nightEnd?hour>=v.nightStart||hour<v.nightEnd:hour>=v.nightStart&&hour<v.nightEnd;const key=[d,type,ot,night,rule.version].join('|');const b=buckets.get(key)||{date:d,type,ot,night,multiplier,nsd:v.nightDifferential,minutes:0,version:rule.version};b.minutes++;buckets.set(key,b)});
let qualifyingMinutes=0;for(const b of buckets.values()){if(!b.ot&&b.type==='ordinary')qualifyingMinutes+=b.minutes;const base=e.hourlyRate*b.minutes/60;let amount=round(base*b.multiplier);if(b.ot)earnings.overtime+=amount;else{const basePay=round(base);if(!baseline)earnings.basic+=basePay;const extra=amount-basePay;if(b.type.includes('Holiday')||b.type.startsWith('special'))earnings.holiday+=extra;else if(b.type==='restDay')earnings.restDay+=baseline?amount:extra;else if(b.type==='companyHoliday')earnings.holiday+=extra;}const nsd=b.night?round(base*b.multiplier*b.nsd):0;earnings.night+=nsd;details.push({...b,label:`${b.type}${b.ot?' overtime':''}${b.night?' + NSD':''}`,amount,nightAmount:nsd,hourlyRate:e.hourlyRate})}
const regularOrdinary=metrics.regularMinutes;return {earnings,metrics,details,qualifiedBasic:baseline?0:round(e.hourlyRate*qualifyingMinutes/60),unearned:baseline&&!rest?round(e.hourlyRate*Math.max(0,normal-regularOrdinary)/60):0}}
