import {validDate,uid,today} from './utils.js';
import {audit} from './storage.js';
export const statuses=['ACTIVE','INACTIVE','SUSPENDED','RESIGNED','TERMINATED'];
export function statusOn(e,date){if(date<e.hireDate)return 'NOT_HIRED';return [...e.statusHistory].filter(h=>h.effectiveDate<=date).sort((a,b)=>a.effectiveDate.localeCompare(b.effectiveDate)||a.timestamp.localeCompare(b.timestamp)).at(-1)?.status||'INACTIVE'}
export const activeOn=(e,date)=>statusOn(e,date)==='ACTIVE';
export function employeeOn(e,date){const r=[...(e.rateHistory||[])].filter(x=>x.effectiveDate<=date).sort((a,b)=>a.effectiveDate.localeCompare(b.effectiveDate)).at(-1);return {...e,...(r?.values||{})}}
export const rateFields=['payrollType','monthlyBasic','weeklyRate','dailyRate','hourlyRate','normalHours','normalDays','restDay','scheduleIn','scheduleOut','breakMinutes','monthlyDivisor','minimumWage','wageBasis','allowance','branch'];
export function saveEmployee(state,input){if(!input.firstName?.trim()||!input.lastName?.trim())throw Error('First and last names are required.');if(!validDate(input.hireDate)||!validDate(input.effectiveDate))throw Error('Valid hire and rate effective dates are required.');if(input.effectiveDate<input.hireDate)throw Error('Salary effective date cannot precede hiring.');if(!(input.hourlyRate>0)||!(input.monthlyBasic>0))throw Error('Enter a positive hourly rate and monthly basic salary.');if(!(input.normalHours>0&&input.normalHours<=8)||!(input.normalDays>=1&&input.normalDays<=6))throw Error('Use 1–8 normal hours and 1–6 normal working days.');if(input.minimumWage&&!input.wageBasis?.trim())throw Error('Enter the applicable regional wage order / basis for MWE status.');const old=state.employees.find(e=>e.id===input.id);if(state.employees.some(e=>e.code===input.code&&e.id!==input.id))throw Error('Employee ID already exists.');if(old&&input.effectiveDate<old.hireDate)throw Error('Invalid effective date.');const {effectiveDate,...fields}=input;const values=Object.fromEntries(rateFields.map(k=>[k,fields[k]]));const rateHistory=[...(old?.rateHistory||[]).filter(x=>x.effectiveDate!==effectiveDate),{effectiveDate,values}];const e={...old,...fields,id:old?.id||uid('EMP'),qrToken:old?.qrToken||crypto.randomUUID(),rateHistory,statusHistory:old?.statusHistory||[{status:'ACTIVE',effectiveDate:input.hireDate,reason:'Hired',changedBy:state.settings.operator,timestamp:new Date().toISOString()}]};if(old)state.employees[state.employees.indexOf(old)]=e;else state.employees.push(e);audit(state,old?'Employee edited':'Employee created',e.code,old||null,e);return e}
export function changeStatus(state,id,status,date,reason){const e=state.employees.find(e=>e.id===id);if(!e||!statuses.includes(status)||!validDate(date)||!reason?.trim())throw Error('Status, effective date, and reason are required.');if(date<e.hireDate)throw Error('Status date precedes hiring.');if(state.payrolls.some(p=>['Approved','Paid'].includes(p.status)&&p.period.to>=date&&p.lines.some(l=>l.employeeId===id)))throw Error('This status date affects a finalized payroll. Use a later effective date or a separate correction.');const old=statusOn(e,date);e.statusHistory.push({status,effectiveDate:date,reason,changedBy:state.settings.operator,timestamp:new Date().toISOString()});audit(state,`Employee ${status.toLowerCase()}`,e.code,old,{status,date,reason})}
