import {esc,money,dateLabel,sum,fullName} from './utils.js';import {paidLines} from './payroll.js';import {generate1601C,generate2316} from './reports.js';
export const preparedLabel='Prepared Payroll/BIR Report – Verify Before Filing';
export const earningLabels={basic:'Basic / regular pay',overtime:'Overtime pay',holiday:'Holiday pay',restDay:'Rest day pay',night:'Night differential',paidLeave:'Paid leave',allowance:'Allowances',bonus:'Bonus',commission:'Commission',other:'Other earnings',thirteenth:'13th month pay',hazard:'Hazard pay',deMinimis:'De minimis benefits'};
export const contributionLabels={sss:'SSS employee (includes MPF)',sssER:'SSS employer (includes MPF)',ec:'Employees’ Compensation',sssMPF:'Employee MPF component',sssMPFER:'Employer MPF component',philhealth:'PhilHealth employee',philhealthER:'PhilHealth employer',pagibig:'Pag-IBIG employee',pagibigER:'Pag-IBIG employer'};
const line=(label,amount,total=false)=>`<div class="ledger-line ${total?'total':''}"><span>${esc(label)}</span><strong>${money(amount)}</strong></div>`;
const head=(c,title,sub)=>`<div class="report-label">${esc(c.name)}</div><h2>${esc(title)}</h2><p class="muted">${esc(sub)}</p><p>${esc(c.address)} · ${esc(c.zip)}</p>`;
export function generatePayslip(state,p,id){const l=p.lines.find(l=>l.employeeId===id);if(!l)throw Error('Payslip not found.');const e=l.employee,year=p.payDate.slice(0,4);const ytd=paidLines(state).filter(x=>x.employeeId===id&&x.payDate.startsWith(year)&&x.payDate<=p.payDate);return `<article class="report-preview">${head(p.company,'Employee payslip',p.number+' · '+p.status)}<div class="report-grid"><div><p><b>${esc(l.name)}</b> · ${esc(e.code)}</p><p>${esc(e.department)} · ${esc(e.position)}</p></div><div><p>Period: ${dateLabel(p.period.from,true)} – ${dateLabel(p.period.to,true)}</p><p>Pay date: ${dateLabel(p.payDate,true)}</p></div></div><div class="report-grid"><section><h3>Earnings</h3>${Object.entries(earningLabels).map(([k,v])=>line(v,l.earnings[k]||0)).join('')}${line('Gross compensation',l.gross,true)}</section><section><h3>Deductions</h3><h4 class="ledger-subhead">Attendance adjustments</h4>${line('Late',l.timeDeductions.late)}${line('Undertime',l.timeDeductions.undertime)}${line('Absence',l.timeDeductions.absence)}<p class="report-note compact">Late, undertime, and absence are displayed separately for transparency and are already reflected in earned basic pay; they are not deducted a second time.</p><h4 class="ledger-subhead">Payroll deductions</h4>${line('SSS',l.contributions.sss)}${line('PhilHealth',l.contributions.philhealth)}${line('Pag-IBIG',l.contributions.pagibig)}${line('Withholding tax',l.tax)}${line('Loans / cash advances',l.loan)}${line('Other deductions',l.otherDeductions)}${line('Total payroll deductions',l.totalDeductions,true)}${line('Net pay',l.net,true)}</section></div><h3>Year to date · paid payrolls</h3>${line('Gross pay',sum(ytd,'gross'))}${line('Taxable compensation',sum(ytd,'taxable'))}${line('Tax withheld',sum(ytd,'tax'))}${line('SSS / PhilHealth / Pag-IBIG',sum(ytd,x=>x.contributions.sss+x.contributions.philhealth+x.contributions.pagibig))}<div class="report-note">Statutory rules used: ${p.ruleSnapshots.map(r=>esc(r.version)+' ('+esc(r.effectiveFrom)+')').join(' · ')}.<br>${e.sample?'SAMPLE DATA. ':''}Prepared from saved payroll records. This document is not proof of bank disbursement.</div></article>`}
export function form1601C(state,month){const r=generate1601C(state,month);return `<article class="report-preview">${head(r.company,'BIR 1601-C · Monthly preparation report',month)}<div class="callout">${preparedLabel}. This worksheet is not the official BIR form and is not an electronic filing.</div><div class="report-grid"><div><p>TIN: ${esc(r.company.tin)}</p><p>RDO: ${esc(r.company.rdo)}</p><p>Category: ${esc(r.company.category)}</p></div><div><p>Contact: ${esc(r.company.contact)}</p><p>Email: ${esc(r.company.email)}</p><p>Employees in paid records: ${r.employeeCount}</p></div></div>${line('Total compensation',r.gross)}<h3 class="mt">Non-taxable compensation</h3>${line('Statutory minimum wage',r.mweBasic)}${line('Qualified MWE holiday / OT / NSD / hazard',r.mwePremiums)}${line('13th month and other exempt benefits',r.benefits)}${line('De minimis benefits',r.deMinimis)}${line('Employee mandatory contributions',r.mandatory)}${line('Other non-taxable compensation',r.otherNonTaxable)}${line('Total non-taxable compensation',r.nonTaxable,true)}${line('Net taxable compensation',r.taxable,true)}${line('Regular / benefit taxes withheld',r.tax-r.adjustments)}${line('Recorded tax adjustments / refunds',r.adjustments)}${line('Tax required to be remitted (before external credits)',r.requiredRemittance,true)}<p class="report-note">Uses Paid payrolls grouped by pay date. Prior remittances, penalties, external credits, minimum-tax-threshold reclassifications, official form line mappings, and filing details require review. Weekly withholding is aggregated, not recomputed using a monthly bracket. A negative result represents a credit requiring BIR treatment review.</p></article>`}
const bir2316Amount=value=>value?new Intl.NumberFormat('en-PH',{minimumFractionDigits:2,maximumFractionDigits:2}).format(value/100):'';
const bir2316Field=(value,x,y,w,h,cls='')=>`<span class="bir2316-value ${cls}" style="left:${(x/1224*100).toFixed(4)}%;top:${(y/1872*100).toFixed(4)}%;width:${(w/1224*100).toFixed(4)}%;height:${(h/1872*100).toFixed(4)}%">${esc(value??'')}</span>`;
const bir2316Money=(value,x,y,w=205,h=32)=>bir2316Field(bir2316Amount(value),x,y,w,h,'amount');
export function form2316(state,year,id){const r=generate2316(state,year,id),e=r.employee,c=r.company;const y=String(year),from=`01/01`,to=`12/31`;const currentBasicTaxable=Math.max(0,r.basic-r.mweBasic);const otherTaxable=Math.max(0,r.otherTaxable);const presentWithheld=r.tax;const totalAdjusted=r.annual.taxWithheld;const fields=[
  bir2316Field(y,249,188,143,31,'center'),bir2316Field(from,773,189,141,30,'center'),bir2316Field(to,1024,189,141,30,'center'),
  bir2316Field(e.tin||'',172,245,441,32,'tin'),bir2316Field(fullName(e),84,296,424,32),bir2316Field(c.rdo||'',518,296,97,32,'center'),
  bir2316Field(e.address||'',85,353,423,30),bir2316Field('',522,353,97,30,'center'),bir2316Field(e.address||'',85,403,423,31),bir2316Field('',523,403,96,31,'center'),
  bir2316Field(e.birthDate||'',93,508,203,30,'center'),bir2316Field(e.contact||'',334,508,285,31,'center'),
  bir2316Money(e.minimumWage?e.dailyRate:0,419,544,199,31),bir2316Money(e.minimumWage?e.monthlyBasic:0,419,581,199,31),
  bir2316Field(c.tin||'',172,670,441,32,'tin'),bir2316Field(c.name||'',84,722,533,31),bir2316Field(c.address||'',85,774,423,31),bir2316Field(c.zip||'',518,776,97,29,'center'),
  bir2316Money(r.mweBasic,967,282),bir2316Money(e.minimumWage?r.holiday:0,967,320),bir2316Money(e.minimumWage?r.overtime:0,967,360),bir2316Money(e.minimumWage?r.night:0,967,401),bir2316Money(e.minimumWage?r.hazard:0,967,441),
  bir2316Money(r.benefits,967,480),bir2316Money(r.deMinimis,967,518),bir2316Money(r.mandatory,967,556),bir2316Money(r.otherNonTaxable,967,595),bir2316Money(r.gross-r.taxable,968,633),
  bir2316Money(currentBasicTaxable,967,709),bir2316Money(otherTaxable,967,1257),bir2316Money(r.taxable,967,1334),
  bir2316Money(r.gross,414,1024),bir2316Money(r.gross-r.taxable,414,1063),bir2316Money(r.taxable,414,1102),bir2316Money(r.annual.previousTaxable,414,1141),bir2316Money(r.annual.taxable,414,1179),bir2316Money(r.annual.taxDue,414,1218),bir2316Money(presentWithheld,414,1257),bir2316Money(r.annual.previousTaxWithheld,414,1296),bir2316Money(totalAdjusted,414,1335),bir2316Money(0,414,1375),bir2316Money(totalAdjusted,414,1414)
];if(e.minimumWage)fields.push(bir2316Field('X',92,620,28,28,'checkbox'));fields.push(bir2316Field('X',229,812,25,25,'checkbox'));return `<article class="bir2316-document"><div class="bir2316-screen-note"><strong>${preparedLabel}</strong><span>Official-form-inspired layout based on the September 2021 (ENCS) Form 2316 supplied for this project. Review every amount before signing or filing.</span></div><div class="bir2316-sheet" role="img" aria-label="BIR Form 2316 prepared for ${esc(fullName(e))}">${fields.join('')}</div><div class="bir2316-screen-foot">Employee: ${esc(fullName(e))} · ${esc(e.code)} · Calendar year ${esc(y)}${e.sample?' · SAMPLE DATA':''}</div></article>`}
export function printReport(html){document.getElementById('print-root').innerHTML=html;window.print()}
export function tabularReport(title,rows,company){if(!rows.length)return `<article class="report-preview">${head(company,title,'Paid payroll records')}<p>No matching records.</p></article>`;return `<article class="report-preview">${head(company,title,'Prepared report · verify before use')}<div class="table-wrap"><table><thead><tr>${Object.keys(rows[0]).map(k=>`<th>${esc(k)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${Object.values(r).map(v=>`<td>${esc(typeof v==='number'?v.toLocaleString('en-PH',{maximumFractionDigits:2}):v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div></article>`}
