import {round,cents,validDate} from './utils.js';
// Demo baseline only. Sources and verification limitations travel with each version.
// Values are centavos except rates, thresholds documented as centavos, and hours.
const version=(version,effectiveFrom,source,values,verification)=>({version,effectiveFrom,effectiveTo:null,source,values,verification,reviewed:false});
const table=(bounds,bases)=>bounds.map((x,i)=>({minimum:cents(x),maximum:i<bounds.length-1?cents(bounds[i+1])-1:null,baseTax:cents(bases[i]),percentage:[0,.15,.20,.25,.30,.35][i],excessOver:cents(x)}));
export function defaultRules(){return [
{kind:'sss',...version('SSS-2025-006','2025-01-01','https://www.sss.gov.ph/sss-contribution-table/',{rows:Array.from({length:61},(_,i)=>{const msc=cents(5000+i*500);return {minimum:i?msc-cents(250):0,maximum:i===60?null:msc+cents(250)-1,msc,employee:round(msc*.05),employer:round(msc*.1),ec:cents(msc>=cents(15000)?30:10),employeeRegular:round(Math.min(msc,cents(20000))*.05),employerRegular:round(Math.min(msc,cents(20000))*.1),employeeMPF:round(Math.max(0,msc-cents(20000))*.05),employerMPF:round(Math.max(0,msc-cents(20000))*.1)}})},'Official employer schedule located; independently verify transcription before real payroll.')},
{kind:'philhealth',...version('PHIC-2024-5PCT','2024-01-01','https://www.philhealth.gov.ph/partners/employers/ContributionTable_v2.pdf',{rate:.05,salaryFloor:cents(10000),salaryCeiling:cents(100000),employeeShare:.5,employerShare:.5},'Official 2024–2025 schedule read; continuing 2026 applicability needs review.')},
{kind:'pagibig',...version('HDMF-460-DEMO','2024-02-01','https://www.pagibigfund.gov.ph/',{threshold:cents(1500),maximumBase:cents(10000),employeeLowRate:.01,employeeRate:.02,employerRate:.02},'Circular 460 could not be retrieved. Unverified demo baseline.')},
{kind:'tax',...version('BIR-2023-ANNEX-E-DEMO','2023-01-01','https://www.bir.gov.ph/withholding-tax',{daily:table([0,685,1096,2192,5479,21918],[0,0,61.65,280.85,1102.6,6034.3]),weekly:table([0,4808,7692,15385,38462,153846],[0,0,432.6,1971.2,7740.45,42355.65]),semiMonthly:table([0,10417,16667,33333,83333,333333],[0,0,937.5,4270.7,16770.7,91770.7]),monthly:table([0,20833,33333,66667,166667,666667],[0,0,1875,8541.8,33541.8,183541.8]),annual:table([0,250000,400000,800000,2000000,8000000],[0,0,22500,102500,402500,2202500]),benefitsExemption:cents(90000)},'Annual rates cross-checked against RA 10963; periodic BIR table transcription awaits official review.')},
{kind:'premiums',...version('LABOR-CODE-DEMO','2023-01-01','https://nwpc.dole.gov.ph/faqs/',{ordinary:1,ordinaryOT:1.25,restDay:1.3,restDayOT:1.69,specialDay:1.3,specialDayOT:1.69,specialDayRestDay:1.5,specialDayRestDayOT:1.95,regularHoliday:2,regularHolidayOT:2.6,regularHolidayRestDay:2.6,regularHolidayRestDayOT:3.38,companyHoliday:1,companyHolidayOT:1.25,nightDifferential:.1,nightStart:22,nightEnd:6},'Base regular-holiday/rest-day/special-day factors cross-checked on DOLE NWPC; complete premium matrix requires current DOLE review.')}
]}
export function selectRule(state,kind,date){const r=state.rules.filter(r=>r.kind===kind&&r.effectiveFrom<=date&&(!r.effectiveTo||date<=r.effectiveTo)).sort((a,b)=>a.effectiveFrom.localeCompare(b.effectiveFrom)).at(-1);if(!r)throw Error(`No ${kind} rule applies on ${date}.`);return r}
export function calculateSSS(compensation,rule){const row=rule.values.rows.find(r=>compensation>=r.minimum&&(r.maximum===null||compensation<=r.maximum));if(!row)throw Error('SSS compensation is outside the configured table.');return {...row,total:row.employee+row.employer+row.ec}}
export function calculatePhilHealth(monthlyBasic,rule){const v=rule.values;const base=Math.max(v.salaryFloor,Math.min(v.salaryCeiling,monthlyBasic));const total=round(base*v.rate);const employee=round(total*v.employeeShare);return {base,total,employee,employer:total-employee}}
export function calculatePagIBIG(compensation,rule){const v=rule.values,base=Math.min(Math.max(0,compensation),v.maximumBase),rate=compensation<=v.threshold?v.employeeLowRate:v.employeeRate;const employee=round(base*rate),employer=round(base*v.employerRate);return {base,rate,employee,employer,total:employee+employer}}
export const contributionKeys=['sss','sssER','ec','sssMPF','sssMPFER','philhealth','philhealthER','pagibig','pagibigER'];
export function monthlyContributions(state,employee,date,sssBase=employee.monthlyBasic,hdmfBase=employee.monthlyBasic){const rules={sss:selectRule(state,'sss',date),philhealth:selectRule(state,'philhealth',date),pagibig:selectRule(state,'pagibig',date)};const s=calculateSSS(sssBase,rules.sss),p=calculatePhilHealth(employee.monthlyBasic,rules.philhealth),h=calculatePagIBIG(hdmfBase,rules.pagibig);return {sss:s.employee,sssER:s.employer,ec:s.ec,sssMPF:s.employeeMPF,sssMPFER:s.employerMPF,philhealth:p.employee,philhealthER:p.employer,pagibig:h.employee,pagibigER:h.employer,details:{sss:s,philhealth:p,pagibig:h},versions:Object.fromEntries(Object.entries(rules).map(([k,r])=>[k,r.version]))}}
export function validateRule(rule){if(!['sss','philhealth','pagibig','tax','premiums'].includes(rule.kind)||!validDate(rule.effectiveFrom)||!rule.version||!rule.source?.startsWith('https://'))throw Error('Rule kind, unique version, effective date, and HTTPS source are required.');if(rule.effectiveTo&&(!validDate(rule.effectiveTo)||rule.effectiveTo<rule.effectiveFrom))throw Error('Invalid rule end date.');function numeric(v){if(typeof v==='number'&&(!Number.isFinite(v)||v<0))throw Error('Rule numbers must be finite and nonnegative.');if(v&&typeof v==='object')Object.values(v).forEach(numeric)}numeric(rule.values);const v=rule.values;if(rule.kind==='sss'){if(!v.rows?.length||v.rows[0].minimum!==0||v.rows.at(-1).maximum!==null)throw Error('SSS brackets must cover 0 through an uncapped last row.');v.rows.forEach((r,i)=>{for(const k of ['minimum','msc','employee','employer','ec','employeeRegular','employerRegular','employeeMPF','employerMPF'])if(!Number.isSafeInteger(r[k]))throw Error('SSS amounts must be integer centavos.');if(i&&v.rows[i-1].maximum+1!==r.minimum)throw Error('SSS brackets must be contiguous.');if(r.employee!==r.employeeRegular+r.employeeMPF||r.employer!==r.employerRegular+r.employerMPF)throw Error('SSS components must reconcile.')})}if(rule.kind==='philhealth'&&(!(v.rate>0&&v.rate<=1)||v.salaryFloor>v.salaryCeiling||v.employeeShare+v.employerShare!==1))throw Error('Invalid PhilHealth configuration.');if(rule.kind==='pagibig'&&(!(v.maximumBase>0)||!(v.employeeRate>0&&v.employeeRate<=1)||!(v.employerRate>0&&v.employerRate<=1)))throw Error('Invalid Pag-IBIG configuration.');if(rule.kind==='tax')for(const f of ['daily','weekly','semiMonthly','monthly','annual']){if(!Array.isArray(v[f])||v[f][0]?.minimum!==0||v[f].at(-1)?.maximum!==null)throw Error(`Invalid ${f} table.`);v[f].forEach((b,i)=>{if(!Number.isSafeInteger(b.minimum)||!Number.isSafeInteger(b.baseTax)||!Number.isSafeInteger(b.excessOver)||!(b.percentage>=0&&b.percentage<=1)||i&&v[f][i-1].maximum+1!==b.minimum)throw Error(`Invalid ${f} bracket.`)})}if(rule.kind==='premiums'){for(const k of Object.keys(defaultRules().find(r=>r.kind==='premiums').values))if(typeof v[k]!=='number')throw Error(`Missing premium ${k}.`);if(v.nightStart>23||v.nightEnd>23)throw Error('Invalid night window.')}return rule}
export function premiumWarnings(rule){if(rule.kind!=='premiums')return [];const base=defaultRules().find(r=>r.kind==='premiums').values;return Object.keys(base).filter(k=>!['nightStart','nightEnd'].includes(k)&&rule.values[k]<base[k]).map(k=>`${k} is below the baseline statutory minimum; legal review is required.`)}
